set nocompatible
filetype off
set exrc 

set encoding=UTF-8


" --- NON PLUGIN CONFIGS

set guifont=Inconsolata\ 14
set fillchars+=vert:\|
syntax enable
set ruler
set hidden
set relativenumber
" set laststatus=2
set mouse=a
set secure
set belloff=all

set smartindent autoindent
set expandtab
set shiftwidth=4
set tabstop=4
set backspace=2


" --- LIMITED SELECTION OF VUNDLE PLUGINS
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim' " Let vundle handle itself

Plugin 'easymotion/vim-easymotion'
Plugin 'scrooloose/nerdtree'
Plugin 'Valloric/YouCompleteMe'
Plugin 'kien/ctrlp.vim'
Plugin 'morhetz/gruvbox'
Plugin 'fatih/vim-go'
Plugin 'vim-fugitive'
Plugin 'xolox/vim-notes'

call vundle#end()
filetype plugin indent on

" --- NERDTree
let NERDTreeIgnore = ['__pycache__', '\.pyc$', '\.o$', '\.so$', '\.a$', '\.swp', '*\.swp', '\.swo', '\.swn', '\.swh', '\.swm', '\.swl', '\.swk', '\.sw*$', '[a-zA-Z]*egg[a-zA-Z]*', '.DS_Store']
let NERDTreeShowHidden=1
let g:NERDTreeWinPos="left"
let g:NERDTreeDirArrows=0
map <C-t> :NERDTreeToggle<CR>

" --- Easymotion
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1
nmap f <Plug>(easymotion-s)

" --- Go
let g:go_def_mapping_enabled = 0

" --- END OF VUNDLE PLUGIN CONFIGS


" --- GVim
if has('gui_running')
    colorscheme gruvbox
	set background=dark
	set colorcolumn=80
	set guioptions-=m " remove menubar
	set guioptions-=T " remove toolbar
	set guioptions-=r " remove right scrollbar
	set guioptions-=L " remove left scrollbar
	set lines=999 columns=999
    autocmd GuiEnter * silent exec '!transset -a 0.90'
endif

command JsonPretty execute ':%!python3 -m json.tool'
